# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(f'np array A: \n {A}')
print(f'A dimension: {A.ndim}')
print(f'A shape: {A.shape}')
print(f'A size: {A.size}')
print(f'A type: {type(A)}')



np array A: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
A dimension: 2
A shape: (3, 5)
A size: 15
A type: <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
result1 = B@C

result2 = np.matmul(B,C)

print('B-C')
print(B-C)
print('\n B*C')
print(B*C)
print( '\n B@C')
print(result1)
print( '\n "matmul"')
print(result2)

B-C
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

 B*C
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

 B@C
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]

 "matmul"
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print('\n Exponentiate each number elementwise (use the np.exp function).')
y = np.exp(D)
print(y)

print(' ')
result = D**2
print(result)

print('\nCalculate the minimum value in the whole matrix.')
min_value = D.min()
print(min_value)

print('\nCalculcate the minimum value in each row.')
min_value_row = D.min(axis = 1)
print(min_value_row)

print('\nCalculcate the minimum value in each column.')
min_value_col = D.min(axis = 0)
print(min_value_col)

print('\nFind the index value for the minimum value in the whole matrix (hint: use np.argmin).')
argmin = np.argmin(D)
print(argmin)

print('\nFind the index value for the minimum value in each row (hint: use np.argmin).')
argmin_row = np.argmin(D, axis=0)
print(argmin_row)

print('\nCalculate the sum for all elements.')
D_sum = np.sum(D)
print(D_sum)

print('\nCalculate the mean for each column.')
D_average_col = np.average(D, axis=0)
print(D_average_col)

print('\nCalculate the median for each column.')
D_median_col = np.median(D, axis=0)
print(D_median_col)



 Exponentiate each number elementwise (use the np.exp function).
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Calculate the minimum value in the whole matrix.
1

Calculcate the minimum value in each row.
[1 4 7]

Calculcate the minimum value in each column.
[1 2 3]

Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
0

Find the index value for the minimum value in each row (hint: use np.argmin).
[0 0 0]

Calculate the sum for all elements.
45

Calculate the mean for each column.
[4. 5. 6.]

Calculate the median for each column.
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [11]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
print(A)
print('\n')
print(f'Skriv ut rad 1 A[1]: {A[1]}')
print('\n')
print(A[: , 0])
print('\n')
print(A[0, :])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Skriv ut rad 1 A[1]: [ 6  7  8  9 10]


[ 1  6 11]


[1 2 3 4 5]


**Answer:**

Angivet index avgränsar urvalet. Motsvarande icke specificerade index/dimensioner tar med allt. 
#A[1] tar med hela raden med index 1. Inget urval på kolumn.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [8]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [9]:
for element in A.flat:
    print(element)
     
#for (i,j), value in np.ndenumerate(A):
#   print(i,  value)



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [10]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)
print()
print('a skapar en np.array med 30 värden')
print('b gör om a till en matris med tre dimensioner/axlar')
print('En array som representerar ett 3-dimensionellt objekt med tre axlar.')
print('-1 fördelar tillgängliga värden i arrayen på aktuell dimension')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

a skapar en np.array med 30 värden
b gör om a till en matris med tre dimensioner/axlar
En array som representerar ett 3-dimensionellt objekt med tre axlar.
-1 fördelar tillgängliga värden i arrayen på aktuell dimension


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [14]:
m1 = np.array([[1, 2], [3, 4]])

m2 = np.array([1, 1])

print(m1 + m2)

#m2.shape

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [16]:
A = np.arange(1, 5).reshape(2,2)
print(A)

print()

b = np.array([2, 2])
print(b)


[[1 2]
 [3 4]]

[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [17]:
def Kalkyl(n1,n2,typ):
    if isinstance(n1,np.ndarray) and isinstance(n2,np.ndarray):
        if typ in ('add','mult'):
            if typ == 'add' and n1.size==n2.size:
                print(n1+n2)
            elif n1.size!=n2.size and typ == 'add': 
                print('Olika storlek på matriserna')
            elif typ == 'mult' and n1.shape[1] == n2.shape[0]:
                print(n1@n2) 
            elif  n1.shape[1] != n2.shape[0]: 
                print('multiplikation av matriserna är inte möjlig')    
        else:
            print ('Ange typ "add" eller "mult"')  
    else:       
        print('Inte numpy arrayer!')


g1 = np.array([[ 2, 2] ])
g2 = np.array([[ 4, 5],[ 4,6]])
g3 = np.array([[ 7, 8] ])
g4='Någon text'


print('Addition')
Kalkyl(g1,g3,'add')
print()
print('Addition olika storlekar på matriserna')
Kalkyl(g1,g2,'add')
print()
print('Multiplikation')
Kalkyl(g1,g2,'mult')
print()
print('Multiplikation inte möjlig')
Kalkyl(g1,g3,'mult')
print()
print('Felaktig typ parameter')
Kalkyl(g1,g3,'multa')
print()
print('Minst en av input parametrarana är inte en numpy array')
Kalkyl(g1,g4,'add')

#Kalkyl(g1,g2,'add')



   

Addition
[[ 9 10]]

Addition olika storlekar på matriserna
Olika storlek på matriserna

Multiplikation
[[16 22]]

Multiplikation inte möjlig
multiplikation av matriserna är inte möjlig

Felaktig typ parameter
Ange typ "add" eller "mult"

Minst en av input parametrarana är inte en numpy array
Inte numpy arrayer!


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [18]:
import math as mh

x=np.array([[4, 3]])

xT=np.transpose(x)

print(f'10.1.1 (a) dimension x: {x.shape}')

print(f'10.1.1 (b) 5x: {5*x}')

print(f'10.1.1 (c) 3x: {3*x}')

print(f'10.1.1 (d) 5x + 3x: {5*x + 3*x}')

print(f'10.1.1 (e) 8x: {8*x}')

print(f'10.1.1 (f) 4x - x: {4*x - x}')

print(f'10.1.1 (g) Ny dimension xT :{xT.shape}')

print(f'10.1.1 (h) Ny x + xT är INTE definierat')

print(f'10.1.1 (i) ||x||: {mh.sqrt(4**2 + 3**2)}')










10.1.1 (a) dimension x: (1, 2)
10.1.1 (b) 5x: [[20 15]]
10.1.1 (c) 3x: [[12  9]]
10.1.1 (d) 5x + 3x: [[32 24]]
10.1.1 (e) 8x: [[32 24]]
10.1.1 (f) 4x - x: [[12  9]]
10.1.1 (g) Ny dimension xT :(2, 1)
10.1.1 (h) Ny x + xT är INTE definierat
10.1.1 (i) ||x||: 5.0


In [20]:
print('\n')
v = np.array([[3],[7],[0],[11]])

print('array v=')
print(v)
print()
print(f'10.1.2 (a) dimension v:\n { v.shape}')

print(f'10.1.2 (b) 2v: \n { 2*v }')

print(f'10.1.2 (c) 5v + 2v \n { (5*v) + (2*v) }')

print(f'10.1.2 (d) 4v - 2v \n { (4*v) - (2*v) }')

vT = np.transpose(v)

print(f'10.1.2 (e) Dimension för vT: { vT.shape }')

print(f'10.1.2 (f) ||v||: {np.sqrt((3)**2 + (7)**2 + (11)**2)} (Roten ur 179)')
      



array v=
[[ 3]
 [ 7]
 [ 0]
 [11]]

10.1.2 (a) dimension v:
 (4, 1)
10.1.2 (b) 2v: 
 [[ 6]
 [14]
 [ 0]
 [22]]
10.1.2 (c) 5v + 2v 
 [[21]
 [49]
 [ 0]
 [77]]
10.1.2 (d) 4v - 2v 
 [[ 6]
 [14]
 [ 0]
 [22]]
10.1.2 (e) Dimension för vT: (1, 4)
10.1.2 (f) ||v||: 13.379088160259652 (Roten ur 179)


In [21]:
print('Uppgift 10.1.3')
print('\n')
#v1 = np.array([4,3,1,5])
#v2 = np.array([2,3,1,51])
v1 = np.array([[4],[3],[1],[5]])
v2 = np.array([[2],[3],[1],[1]])

v1T = np.transpose(v1)

print(f'10.1.3 (a) ||v1||: {mh.sqrt(4**2+3**2+1**2+5**2)}')

v3 = v1 - v2
#print(v3)

print(f'10.1.3 (b) ||v1-v2||: {mh.sqrt((2)**2+(4)**2)}')



Uppgift 10.1.3


10.1.3 (a) ||v1||: 7.14142842854285
10.1.3 (b) ||v1-v2||: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [22]:
print('\n Övningsuppgifter 10.2')

A= np.array( [[2, 1, -1], [1, -1, 1]] )

B= np.array( [[4, -2, 1], [2, -4, -2 ]] )

C= np.array( [[1, 2], [2, 1]] )

D= np.array( [[3, 4], [4, 3]] )

E= np.array( [[1 ,2]])

I= np.array( [[1 ,0], [0 ,1 ] ])

print(f'10.2.1 (a) 2A: \n{2*A}')

print(f'\n10.2.1 (b) B - 2A: \n{B - (2*A)}')

#print(3*C)
#print(2*E)
print()
#print(C.shape)
#print(E.shape)

print(f'10.2.1 (c) 3C - 2E: Ej deinierad')

print(f'\n10.2.1 (d) 2D - 3C: \n{(2*D) - (3*C)}')

DT = np.transpose(D)
print(f'\n10.2.1 (e) 2D - 3C: \n{(DT) + (2*D)}')

CT = np.transpose(C)

print()
#print(CT)
#print(DT)
print(f'\n10.2.1 (f) 2CT - 2DT: \n{(2*CT) - (2*DT)}')

AT = np.transpose(A)
print('\n')
#print(AT.shape)
#print(B.shape)
print(f'10.2.1 (g) AT - B : \nEj definierad!')


#v2 = np.array([2,3,1,51])
#v1 = np.array([[4],[3],[1],[5]])
#v2 = np.array([[2],[3],[1],[1]])
#print(B - 2*A)


 Övningsuppgifter 10.2
10.2.1 (a) 2A: 
[[ 4  2 -2]
 [ 2 -2  2]]

10.2.1 (b) B - 2A: 
[[ 0 -4  3]
 [ 0 -2 -4]]

10.2.1 (c) 3C - 2E: Ej deinierad

10.2.1 (d) 2D - 3C: 
[[3 2]
 [2 3]]

10.2.1 (e) 2D - 3C: 
[[ 9 12]
 [12  9]]


10.2.1 (f) 2CT - 2DT: 
[[-4 -4]
 [-4 -4]]


10.2.1 (g) AT - B : 
Ej definierad!


In [23]:
print()
#print(AT.shape)
#print(B.shape)
print(f'10.2.1 (h) AC : Ej definierad!')
print()

#print(C)
#print(D)

print(f'10.2.1 (i) CD: \n{(C)@(D)}')

print()
#print(f'10.2.1 (j) CB: \n{(C)*(B) }')
print()
print(f'10.2.1 (j) CB: Inte möjlig')
print()
print(f'10.2.1 (k) CI: \n{(C)@(I) }')
print()
BT = np.transpose(B)
print('10.2.1(l)ABT: MMultiplikation ej möjlig pga size på matriserna')
Kalkyl(A,BT,'mult')


10.2.1 (h) AC : Ej definierad!

10.2.1 (i) CD: 
[[11 10]
 [10 11]]


10.2.1 (j) CB: Inte möjlig

10.2.1 (k) CI: 
[[1 2]
 [2 1]]

10.2.1(l)ABT: MMultiplikation ej möjlig pga size på matriserna
[[5 2]
 [7 4]]


In [24]:
#10.2.2#
A=np.array([[2,3,4],[5,4,1]])

#print(A)

B = np.transpose(A)

#print(B)

print()
print(f'10.2.2 CD: \n{(C)*(D) }')
print(A@B)

#print(A.shape)


10.2.2 CD: 
[[3 8]
 [8 3]]
[[29 26]
 [26 42]]


In [25]:
#10.2.3
print('10.2.3')
A=np.array([[1,2],[2,4]])
B=np.array([[2,1],[1,3]])
C=np.array([[4,3],[0,2]])

print('A@B')
print(A@B)
print('A@C')
print(A@C)
print()
#print(B)
#print(C)



10.2.3
A@B
[[ 4  7]
 [ 8 14]]
A@C
[[ 4  7]
 [ 8 14]]



### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [26]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v1.base)
print(v2)
print(v2.base)
print('v1 och v2 har samma data men olika objekt som använder dessa,\nv2.base visar ursprunglig, bakomliggande data')
print()
v2[1]=123
print
print(v1)
print(v2)


[0 1 2 3]
None
[2 3]
[0 1 2 3]
v1 och v2 har samma data men olika objekt som använder dessa,
v2.base visar ursprunglig, bakomliggande data

[  0   1   2 123]
[  2 123]
